//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce_With_AD_Posting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECommerce_With_AD_PostingEntities1 : DbContext
    {
        public ECommerce_With_AD_PostingEntities1()
            : base("name=ECommerce_With_AD_PostingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_admin> tbl_admin { get; set; }
        public DbSet<tbl_cateogry> tbl_cateogry { get; set; }
        public DbSet<tbl_invoice> tbl_invoice { get; set; }
        public DbSet<tbl_order> tbl_order { get; set; }
        public DbSet<tbl_product> tbl_product { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
    }
}
